param(
    [string]$TargetDir = (Join-Path $PSScriptRoot "..\Bot Engine")
)

$ErrorActionPreference = "Stop"

$TargetDir = (Resolve-Path -Path $TargetDir).Path
Set-Location -Path $TargetDir

function ConvertTo-DotEnvValue {
    param([string]$Value)

    if ($null -eq $Value) {
        return ""
    }

    $Text = [string]$Value
    if ($Text -match '[\s#"]') {
        $Escaped = $Text.Replace('\', '\\').Replace('"', '\"')
        return '"' + $Escaped + '"'
    }

    return $Text
}

if (Test-Path ".env") {
    Write-Host ".env already exists. No changes made."
    exit 0
}

Write-Host "This setup creates a local .env file only."
Write-Host "Your MT5 password will not be committed to GitHub."
Write-Host ""

$Login = Read-Host "MT5 login [Press Enter to pull dynamically from Supabase Dashboard]"
if ([string]::IsNullOrWhiteSpace($Login)) {
    Write-Host "[INFO] MT5 login left blank. The bot will load this dynamically from Supabase at runtime."
    $Login = "12345678" # Default placeholder in config
}

$Password = ""

$Server = Read-Host "MT5 server [Press Enter to pull dynamically from Supabase Dashboard]"
if ([string]::IsNullOrWhiteSpace($Server)) {
    if ($Login -eq "12345678") {
        Write-Host "[INFO] MT5 server left blank. The bot will load this dynamically from Supabase at runtime."
    }
    $Server = "Broker-Server" # Default placeholder in config
}

$Symbols = "XAUUSD"
Write-Host "Trading symbols: $Symbols"

$OpenRouterKey = ""
$HfToken = ""
$FallbackEnabled = "False"

$MainModel = "openai/gpt-oss-20b:free"
$RiskModel = "openai/gpt-oss-120b:free"
$RiskReview = "True"
Write-Host "Main AI model: $MainModel"
Write-Host "Risk AI model: $RiskModel"
Write-Host "Risk review: $RiskReview"

$EnvContent = @"
# ============================================================
# .env - Local settings for AI Trading Bot
# Generated by Setup/setup_env.bat
# NEVER commit this file to version control.
# ============================================================

# MT5 Account Credentials
MT5_LOGIN=$(ConvertTo-DotEnvValue $Login)
MT5_PASSWORD=$(ConvertTo-DotEnvValue $Password)
MT5_SERVER=$(ConvertTo-DotEnvValue $Server)
# MT5_PATH=C:/Program Files/MetaTrader 5/terminal64.exe

# Trading Settings
SYMBOLS=$(ConvertTo-DotEnvValue $Symbols)
TIMEFRAME=M5
LOOP_INTERVAL=60
BARS_TO_FETCH=100

# Risk Management
MAX_RISK_PERCENT=2.0
MAX_CONSECUTIVE_LOSSES=3
MIN_CONFIDENCE=0.60
SL_PIPS=50
TP_PIPS=100
MIN_LOT=0.01
MAX_LOT=1.0

# Cloud AI Settings
AI_PROVIDER=openrouter
AI_FALLBACK_PROVIDER=huggingface
AI_FALLBACK_ENABLED=$FallbackEnabled
OPENROUTER_API_KEY=$(ConvertTo-DotEnvValue $OpenRouterKey)
OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
OPENROUTER_APP_NAME=Investment-AI_T
OPENROUTER_SITE_URL=https://github.com/hdanial211/Investment-AI_T
HF_TOKEN=$(ConvertTo-DotEnvValue $HfToken)
HF_BASE_URL=https://router.huggingface.co/v1
AI_MAIN_MODEL=$(ConvertTo-DotEnvValue $MainModel)
AI_RISK_MODEL=$(ConvertTo-DotEnvValue $RiskModel)
AI_FALLBACK_MODEL=qwen/qwen3-next-80b-a3b-instruct:free
HF_MAIN_MODEL=Qwen/Qwen3-4B-Instruct-2507
HF_RISK_MODEL=deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
ENABLE_RISK_REVIEW=$(ConvertTo-DotEnvValue $RiskReview)
AI_STARTUP_HEALTHCHECK=False
AI_TIMEOUT=300
AI_RETRIES=2
AI_TEMPERATURE=0.1
AI_MAX_TOKENS=256

# Future Vision AI / Chart Screenshot
VISION_AI_ENABLED=False
CHART_IMAGE_SOURCE=browser_automation
CHART_IMAGE_TIMEFRAMES=H4,H1,M30,M15,M5,M1
TRADINGVIEW_CHART_URL=
MT5_SCREENSHOT_DIR=chart_screenshots

# Supabase Sync (read-only Vercel dashboard integration)
SUPABASE_URL=https://kusyjtpcjyflxgfcqenb.supabase.co
SUPABASE_ANON_KEY=sb_publishable_Pdf-F-j3PH3keLsZ8ZoEZA_tbotGoxM
SUPABASE_SERVICE_ROLE_KEY=
SUPABASE_SYNC_ENABLED=True
SUPABASE_MACHINE_ID=laptop-main
SUPABASE_REQUEST_TIMEOUT=10

# Virtual Exit / Trade Management
USE_BROKER_SL_TP=False
USE_VIRTUAL_SL_TP=True
USE_VIRTUAL_TRAILING_STOP=True
VIRTUAL_EXIT_CHECK_INTERVAL=10
MAX_TRADES_PER_PAIR=10

# Pattern Usage Dashboard
PATTERN_USAGE_SYNC_ENABLED=False
PATTERN_PRIMARY_LIMIT=1
PATTERN_CONFLUENCE_LIMIT=8
PATTERN_STATS_UPDATE_INTERVAL=10

# Logging
LOG_LEVEL=INFO
"@

Set-Content -Path ".env" -Value $EnvContent -Encoding UTF8
Write-Host ""
Write-Host ".env created successfully."
Write-Host "Provider: OpenRouter"
Write-Host "Main model: $MainModel"
Write-Host "Risk model: $RiskModel"
Write-Host "Risk review: $RiskReview"
