param(
    [string]$TargetDir = (Join-Path $PSScriptRoot "..\Bot Engine")
)

$ErrorActionPreference = "Stop"

$TargetDir = (Resolve-Path -Path $TargetDir).Path
Set-Location -Path $TargetDir

function ConvertTo-DotEnvValue {
    param([string]$Value)

    if ($null -eq $Value) {
        return ""
    }

    $Text = [string]$Value
    if ($Text -match '[\s#"]') {
        $Escaped = $Text.Replace('\', '\\').Replace('"', '\"')
        return '"' + $Escaped + '"'
    }

    return $Text
}

if (Test-Path ".env") {
    Write-Host ".env already exists. No changes made."
    exit 0
}

Write-Host "This setup creates a local .env file only."
Write-Host "Your MT5 password will not be committed to GitHub."
Write-Host ""

$Login = Read-Host "MT5 login"
if ([string]::IsNullOrWhiteSpace($Login)) {
    throw "MT5 login is required."
}

$SecurePassword = Read-Host "MT5 password" -AsSecureString
$PasswordPtr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecurePassword)
try {
    $Password = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($PasswordPtr)
}
finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($PasswordPtr)
}

if ([string]::IsNullOrWhiteSpace($Password)) {
    throw "MT5 password is required."
}

$Server = Read-Host "MT5 server [RoboForex-Pro]"
if ([string]::IsNullOrWhiteSpace($Server)) {
    $Server = "RoboForex-Pro"
}

$Symbols = "XAUUSD,EURUSD"
Write-Host "Trading symbols: $Symbols"

$OpenRouterKey = Read-Host "OpenRouter API key (starts sk-or-v1)"
if ([string]::IsNullOrWhiteSpace($OpenRouterKey)) {
    throw "OpenRouter API key is required for cloud AI mode."
}

$HfToken = Read-Host "Hugging Face token for fallback [optional]"
$FallbackEnabled = "True"
if ([string]::IsNullOrWhiteSpace($HfToken)) {
    $FallbackEnabled = "False"
}

$MainModel = "openai/gpt-oss-20b:free"
$RiskModel = "openai/gpt-oss-120b:free"
$RiskReview = "True"
Write-Host "Main AI model: $MainModel"
Write-Host "Risk AI model: $RiskModel"
Write-Host "Risk review: $RiskReview"

$EnvContent = @"
# ============================================================
# .env - Local settings for AI Trading Bot
# Generated by Setup/setup_env.bat
# NEVER commit this file to version control.
# ============================================================

# MT5 Account Credentials
MT5_LOGIN=$(ConvertTo-DotEnvValue $Login)
MT5_PASSWORD=$(ConvertTo-DotEnvValue $Password)
MT5_SERVER=$(ConvertTo-DotEnvValue $Server)
# MT5_PATH=C:/Program Files/MetaTrader 5/terminal64.exe

# Trading Settings
SYMBOLS=$(ConvertTo-DotEnvValue $Symbols)
TIMEFRAME=M5
LOOP_INTERVAL=10
BARS_TO_FETCH=100

# Risk Management
MAX_RISK_PERCENT=2.0
MAX_CONSECUTIVE_LOSSES=3
MIN_CONFIDENCE=0.60
SL_PIPS=50
TP_PIPS=100
MIN_LOT=0.01
MAX_LOT=1.0

# Cloud AI Settings
AI_PROVIDER=openrouter
AI_FALLBACK_PROVIDER=huggingface
AI_FALLBACK_ENABLED=$FallbackEnabled
OPENROUTER_API_KEY=$(ConvertTo-DotEnvValue $OpenRouterKey)
OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
OPENROUTER_APP_NAME=Investment-AI_T
OPENROUTER_SITE_URL=https://github.com/hdanial211/Investment-AI_T
HF_TOKEN=$(ConvertTo-DotEnvValue $HfToken)
HF_BASE_URL=https://router.huggingface.co/v1
AI_MAIN_MODEL=$(ConvertTo-DotEnvValue $MainModel)
AI_RISK_MODEL=$(ConvertTo-DotEnvValue $RiskModel)
AI_FALLBACK_MODEL=qwen/qwen3-next-80b-a3b-instruct:free
HF_MAIN_MODEL=Qwen/Qwen3-4B-Instruct-2507
HF_RISK_MODEL=deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
ENABLE_RISK_REVIEW=$(ConvertTo-DotEnvValue $RiskReview)
AI_STARTUP_HEALTHCHECK=False
AI_TIMEOUT=300
AI_RETRIES=2
AI_TEMPERATURE=0.1
AI_MAX_TOKENS=256

# Supabase Sync (future dashboard integration)
SUPABASE_URL=
SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
SUPABASE_SYNC_ENABLED=False
SUPABASE_MACHINE_ID=laptop-main

# Virtual Exit / Trade Management
USE_BROKER_SL_TP=True
USE_VIRTUAL_SL_TP=False
USE_VIRTUAL_TRAILING_STOP=False
VIRTUAL_EXIT_CHECK_INTERVAL=10

# Logging
LOG_LEVEL=INFO
"@

Set-Content -Path ".env" -Value $EnvContent -Encoding UTF8
Write-Host ""
Write-Host ".env created successfully."
Write-Host "Provider: OpenRouter"
Write-Host "Main model: $MainModel"
Write-Host "Risk model: $RiskModel"
Write-Host "Risk review: $RiskReview"
