param(
    [string]$TargetDir = (Join-Path $PSScriptRoot "..\Bot Engine")
)

$ErrorActionPreference = "Stop"

$TargetDir = (Resolve-Path -Path $TargetDir).Path
Set-Location -Path $TargetDir

function ConvertTo-DotEnvValue {
    param([string]$Value)

    if ($null -eq $Value) {
        return ""
    }

    $Text = [string]$Value
    if ($Text -match '[\s#"]') {
        $Escaped = $Text.Replace('\', '\\').Replace('"', '\"')
        return '"' + $Escaped + '"'
    }

    return $Text
}

if (Test-Path ".env") {
    Write-Host ".env already exists. No changes made."
    exit 0
}

Write-Host "This setup creates a local .env file only."
Write-Host "Your MT5 password will not be committed to GitHub."
Write-Host ""

$Login = Read-Host "MT5 login"
if ([string]::IsNullOrWhiteSpace($Login)) {
    throw "MT5 login is required."
}

$SecurePassword = Read-Host "MT5 password" -AsSecureString
$PasswordPtr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecurePassword)
try {
    $Password = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($PasswordPtr)
}
finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($PasswordPtr)
}

if ([string]::IsNullOrWhiteSpace($Password)) {
    throw "MT5 password is required."
}

$Server = Read-Host "MT5 server [RoboForex-Pro]"
if ([string]::IsNullOrWhiteSpace($Server)) {
    $Server = "RoboForex-Pro"
}

$Symbols = Read-Host "Trading symbols [XAUUSD,EURUSD]"
if ([string]::IsNullOrWhiteSpace($Symbols)) {
    $Symbols = "XAUUSD,EURUSD"
}

$Model = Read-Host "Ollama main model [qwen2.5:7b]"
if ([string]::IsNullOrWhiteSpace($Model)) {
    $Model = "qwen2.5:7b"
}

$RiskReview = Read-Host "Enable DeepSeek risk review? Type True or False [True]"
if ([string]::IsNullOrWhiteSpace($RiskReview)) {
    $RiskReview = "True"
}

$EnvContent = @"
# ============================================================
# .env - Local settings for AI Trading Bot
# Generated by Setup/setup_env.bat
# NEVER commit this file to version control.
# ============================================================

# MT5 Account Credentials
MT5_LOGIN=$(ConvertTo-DotEnvValue $Login)
MT5_PASSWORD=$(ConvertTo-DotEnvValue $Password)
MT5_SERVER=$(ConvertTo-DotEnvValue $Server)
# MT5_PATH=C:/Program Files/MetaTrader 5/terminal64.exe

# Trading Settings
SYMBOLS=$(ConvertTo-DotEnvValue $Symbols)
TIMEFRAME=M5
LOOP_INTERVAL=10
BARS_TO_FETCH=100

# Risk Management
MAX_RISK_PERCENT=2.0
MAX_CONSECUTIVE_LOSSES=3
MIN_CONFIDENCE=0.60
SL_PIPS=50
TP_PIPS=100
MIN_LOT=0.01
MAX_LOT=1.0

# Ollama Settings
OLLAMA_URL=http://localhost:11434/api/generate
OLLAMA_MODEL=$(ConvertTo-DotEnvValue $Model)
OLLAMA_RISK_MODEL=deepseek-r1:8b
ENABLE_RISK_REVIEW=$(ConvertTo-DotEnvValue $RiskReview)
OLLAMA_TIMEOUT=300
OLLAMA_RETRIES=3
OLLAMA_TEMPERATURE=0.1
OLLAMA_TOP_P=0.9
OLLAMA_NUM_CTX=4096
OLLAMA_NUM_PREDICT=256
OLLAMA_NUM_GPU=999
OLLAMA_KEEP_ALIVE=10m

# Logging
LOG_LEVEL=INFO
"@

Set-Content -Path ".env" -Value $EnvContent -Encoding UTF8
Write-Host ""
Write-Host ".env created successfully."
Write-Host "Main model: $Model"
Write-Host "Risk review: $RiskReview"
